# Generated by Django 5.1.3 on 2024-12-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_producto_url_imagen_alter_intercambio_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='accion',
            field=models.CharField(choices=[('venta', 'Venta'), ('intercambio', 'Intercambio'), ('donacion', 'Donación')], default='venta', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('libros', 'Libros'), ('muebles', 'Muebles')], default='ropa', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Catalogo',
        ),
    ]
