# Generated by Django 5.1.3 on 2024-12-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_producto_estado_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='accion',
            field=models.CharField(choices=[('venta', 'Venta'), ('intercambio', 'Intercambio'), ('donacion', 'Donación')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
