# Generated by Django 5.1.3 on 2024-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_producto_options_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_intercambio',
            field=models.CharField(blank=True, choices=[('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('libros', 'Libros'), ('muebles', 'Muebles')], max_length=20, null=True, verbose_name='Categoría de Intercambio'),
        ),
    ]
