# Generated by Django 5.1.3 on 2024-12-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_producto_categoria_intercambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_intercambio',
        ),
    ]
